baseURL = 'https://shekhawat.site/'
locale = 'en-us'
title= "Parakram Singh Shekhawat"
disableKinds = ["taxonomy", "term"]

theme = 'poison'

[params]
	brand = "Parakram Singh Shekhawat"
	brand_image = "/images/digital_cat_art.jpeg"
	dark_mode = true
	pluralizelisttitles = false
	menu = [
		{ Name = "About", URL = "/about/", HasChildren = false },
		{ Name = "CV", URL = "https://drive.google.com/file/d/1Ne5ARQEwexRyINKjhuvBWmbxBvOMDitZ/view?usp=sharing", HasChildren = false, External = true },
		{ Name = "Projects", URL = "/projects/", HasChildren = true, Limit = 10 },
		{ Name = "Updates", URL = "/updates/", HasChildren = false },
	]
	github_url = "https://github.com/shekhawatxyz"
	linkedin_url = "https://www.linkedin.com/in/parakram-singh-shekhawat-405a971b7"
	rss_icon = true
